[bot]
prefixes = ["c!", "d!"]
description = """Discord Version 4 of DuckHunt, the popular game bot"""
playing = "Ducks are everywhere"
commands_are_case_insensitive = true

[database]
# A postgreSQL database to store information about users, channels, and guilds
# Please ensure the database exist before loading the database modules
# Quick Start : https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e
enable = true
host = "127.0.0.1"
port = "5432"
user = "mybot"
password = "mybot"
database = "mybot"

[permissions.default]
# Permissions work on a inheritance basis
# First, default permissions here are applied. They usually deny almost everything but the base functions of the bot.
# Then, Guild permissions are applied and remplace some default permisions. After that, special member permissions are
# applied. Finally, Fixed permissions below are applied to prevent giving too much rights (like bot.administrator) in a
# server or a memeber config. Then, if there are some, user permissions are applied and are allowed to override anything.
# They are set by the bot admins, in the db.
# Once the permissions are calculated, they are applied from precise to imprecise (wildcards).
# For example, suppose the bot is checking for a.b.c, and the user has a.* allowed, a.b.* denied, and a.b.c allowed,
# the permission is granted by a.b.c since it's the most specific of all.
# WARNING : Ensure that all permissions names are lowercased.
# Dont forget that each command have, by default and unless another check exists, a permission going by the form
# CogName.command_name. As you might see in [permissions.fixed], they are by default evaluted to false. So if you want
# to make them by-default accessible to anyone, you have to give that permission (or a lower wildcard) here.
"server.ignored" = false
"simplecommands.*" = true
"databasecommands.*" = true
"permissionscommands.*" = true

[permissions.fixed]
# We need to deny that one to everyone, because by default there is no permissions granted
"*" = false

# Bot permissions are special and must not be overridden
# "Just in case"
"bot.*" = false

# These need to be overriden "per-user" in the database.
"bot.bypass_cooldowns" = false
"bot.ignored"         = false
"bot.administrator"    = false

[ducks.images]
emoji = "https://media.discordapp.net/attachments/734810933091762188/735596788408385750/PicsArt_07-22-03.38.37.png"
glare = "https://cdn.discordapp.com/emojis/436542355257163777.png"
eyebrows = "https://cdn.discordapp.com/emojis/436542355504627712.png"

[ducks.ascii.normal]
traces = ["-,_,.-'`'°-,_,.-'`'°", "-,..,.-'`'°-,_,.-'`'°", "-._..-'`'°-,_,.-'`'°", "-,_,.-'`'°-,_,.-''`"]
faces  = ["\\_O<", "\\_o<", "\\_Õ<", "\\_õ<", "\\_Ô<", "\\_ô<", "\\_Ö<", "\\_ö<", "\\_Ø<", "\\_ø<", "\\_Ò<", "\\_ò<", "\\_Ó<", "\\_ó<", "\\_0<", "\\_©<", "\\_@<", "\\_º<", "\\_°<",
          "\\_^<", "/_O<", "/_o<", "/_Õ<", "/_õ<", "/_Ô<", "/_ô<", "/_Ö<", "/_ö<", "/_Ø<", "/_ø<", "/_Ò<", "/_ò<", "/_Ó<", "/_ó<", "/_0<", "/_©<", "/_@<", "/_^<", "§_O<", "§_o<",
          "§_Õ<", "§_õ<", "§_Ô<", "§_ô<", "§_Ö<", "§_ö<", "§_Ø<", "§_ø<", "§_Ò<", "§_ò<", "§_Ó<", "§_ó<", "§_0<", "§_©<", "§_@<", "§_º<", "§_°<", "§_^<", "\\_O-", "\\_o-", "\\_Õ-",
          "\\_õ-", "\\_Ô-", "\\_ô-", "\\_Ö-", "\\_ö-", "\\_Ø-", "\\_ø-", "\\_Ò-", "\\_ò-", "\\_Ó-", "\\_ó-", "\\_0-", "\\_©-", "\\_@-", "\\_º-", "\\_°-", "\\_^-", "/_O-", "/_o-",
          "/_Õ-", "/_õ-", "/_Ô-", "/_ô-", "/_Ö-", "/_ö-", "/_Ø-", "/_ø-", "/_Ò-", "/_ò-", "/_Ó-", "/_ó-", "/_0-", "/_©-", "/_@-", "/_^-", "§_O-", "§_o-", "§_Õ-", "§_õ-", "§_Ô-",
          "§_ô-", "§_Ö-", "§_ö-", "§_Ø-", "§_ø-", "§_Ò-", "§_ò-", "§_Ó-", "§_ó-", "§_0-", "§_©-", "§_@-", "§_^-", "\\_O{", "\\_o{", "\\_Õ{", "\\_õ{", "\\_Ô{", "\\_ô{",
          "\\_Ö{", "\\_ö{", "\\_Ø{", "\\_ø{", "\\_Ò{", "\\_ò{", "\\_Ó{", "\\_ó{", "\\_0{", "\\_©{", "\\_@{", "\\_º{", "\\_°{", "\\_^{", "/_O{", "/_o{", "/_Õ{",
          "/_õ{", "/_Ô{", "/_ô{", "/_Ö{", "/_ö{", "/_Ø{", "/_ø{", "/_Ò{", "/_ò{", "/_Ó{", "/_ó{", "/_0{", "/_©{", "/_@{", "/_^{", "§_O{", "§_o{", "§_Õ{", "§_õ{",
          "§_Ô{", "§_ô{", "§_Ö{", "§_ö{", "§_Ø{", "§_ø{", "§_Ò{", "§_ò{", "§_Ó{", "§_ó{", "§_0{", "§_©{", "§_@{", "§_º{", "§_°{", "§_^{"]
emojis = ["<a:a_Duck_01:439546956986187777>", "<:official_Duck_01_reversed:439576463436546050>"]
shouts = ["COIN", "COIN", "COIN", "COIN", "COIN", "KWAK", "KWAK", "KWAAK", "KWAAK", "KWAAAK", "KWAAAK", "COUAK", "COUAK", "COUAAK", "COUAAK", "COUAAAK", "COUAAAK", "QUAK", "QUAK",
          "QUAAK", "QUAAK", "QUAAAK", "QUAAAK", "QUACK", "QUACK", "QUAACK", "QUAACK", "QUAAACK", "QUAAACK", "COUAC", "COUAC", "COUAAC", "COUAAC", "COUAAAC", "COUAAAC", "COUACK", "COUACK"]

[[ducks.webhooks_parameters.normal]]
username = "A duck"
avatar_url = "emoji"

[[ducks.webhooks_parameters.normal]]
username = "Mr. Duck"
avatar_url = "emoji"

[[ducks.webhooks_parameters.normal]]
username = "Cool duck"
avatar_url = "emoji"

[[ducks.webhooks_parameters.normal]]
username = "Donald"
avatar_url = "emoji"

[[ducks.webhooks_parameters.normal]]
username = "Nice duck"
avatar_url = "emoji"

[[ducks.webhooks_parameters.normal]]
username = "Standard duck"
avatar_url = "emoji"

[[ducks.webhooks_parameters.super]]
username = "Big duck"
avatar_url = "glare"

[[ducks.webhooks_parameters.super]]
username = "Big duck energy"
avatar_url = "glare"

[[ducks.webhooks_parameters.super]]
username = "Daddy duck"
avatar_url = "glare"

[[ducks.webhooks_parameters.super]]
username = "Heavy duck"
avatar_url = "eyebrows"


[auth.discord]
# Your bot token. You can find it on the Bot page of the Developper portal
token = ""

[cogs]
# Names of cogs to load. Usually cogs.file_name_without_py
cogs_to_load = ['jishaku', 'cogs.error_handling', 'cogs.simple_commands', 'cogs.background_loop', 'cogs.support_server_commands', 'cogs.database_commands', 'cogs.permissions_commands', 'cogs.ducks_spawning_commands']

# The name after cogs is the name of the class
[cogs.SimpleCommands]
hello_message = "Hello there!"

[cogs.SupportServerCommands]
# That's the ID of your server where the command will be ran
support_server_id = 734810932529856652
# ID of an empty channel that will be used as a status dashboard.
status_channel_id = 734879974842171474