[bot]
prefixes = ["c!", "d!", "C!", "D!"]
description = """Discord Version 4 of DuckHunt, the popular game bot"""
playing = "Ducks are everywhere"
commands_are_case_insensitive = true

[database]
# A postgreSQL database to store information about users, channels, and guilds
# Please ensure the database exist before loading the database modules
# Quick Start : https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e
enable = true
host = "127.0.0.1"
port = "5432"
user = "mybot"
password = "mybot"
database = "mybot"


[auth.discord]
# Your bot token. You can find it on the Bot page of the Developper portal
token = ""

[cogs]
# Names of cogs to load. Usually cogs.file_name_without_py
cogs_to_load = ['jishaku',
                'cogs.error_handling',
                'cogs.simple_commands',
                'cogs.background_loop',
                'cogs.support_server_commands',
                'cogs.settings_commands',
                'cogs.ducks_spawning_commands',
                'cogs.ducks_spawning',
                'cogs.ducks_hunting_commands',
                'cogs.statistics_experience_commands',
                'cogs.community',
                'cogs.inventory_commands',
                'cogs.shopping_commands',
                'cogs.duck_boss',
                ]

# The name after cogs is the name of the class
[cogs.SimpleCommands]
wiki_url = "https://docs.duckhunt.me"

[cogs.DuckBoss]
boss_channel_id = 779506107428241450
required_bangs = 450


[cogs.SupportServerCommands]
# That's the ID of your server where the command will be ran
support_server_id = 734810932529856652
# ID of an empty channel that will be used as a status dashboard.
status_channel_id = 734879974842171474

[cogs.Community]
servers = [195260081036591104]
rpg_role_name = "Ping me for RPG bot events"